version: '3.7'

services:
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  frontin-proxy:
    container_name: frontin-proxy
    environment:
      - PROXY_HTTP_SERVER_PORT=${PROXY_HTTP_SERVER_PORT:-80}
      - PROXY_HTTPS_SERVER_PORT=${PROXY_HTTPS_SERVER_PORT:-443}
      - PROXY_SERVER_HOST=${PROXY_SERVER_HOST:-localhost}
      - PROXY_DOMAIN=${VUE_APP_DOMAIN}
      - PROXY_EXTENSION=${PROXY_EXTENSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_URL=${BASE_URL:-/}
        - VUE_APP_NAME=${VUE_APP_NAME:-frontin}
        - VUE_APP_CLIENT_URL=${VUE_APP_CLIENT_URL}
        - VUE_APP_SERVER_URL=${VUE_APP_SERVER_URL}
        - VUE_APP_ROOT_API=${VUE_APP_ROOT_API}
        - VUE_APP_LOGGER_LEVEL=${VUE_APP_LOGGER_LEVEL:-2}
        - VUE_APP_GIT_LINK=https://github.com/getlarge/frontin/
        - VUE_APP_GIT_COMPONENTS_PATH=tree/master/src/components
        - VUE_APP_DOMAIN=${VUE_APP_DOMAIN}
    restart: always
    volumes:
      - ./deploy/nginx/nignx-production.template:/etc/nginx/nginx.template
      - ./deploy/certbot/www:/var/www/certbot
      - ./deploy/certbot/conf:/etc/letsencrypt
      # - ./log/nginx:/var/log/nginx
    ports:
      - '${PROXY_HTTP_SERVER_PORT:-80}:${PROXY_HTTP_SERVER_PORT:-80}'
      - '${PROXY_HTTPS_SERVER_PORT:-443}:${PROXY_HTTPS_SERVER_PORT:-443}'
